FROM elasticsearch:latest

RUN /usr/share/elasticsearch/bin/plugin install lmenezes/elasticsearch-kopf/2.0 \
/usr/share/elasticsearch/bin/plugin install analysis-phonetic \
/usr/share/elasticsearch/bin/plugin install  install https://github.com/NLPchina/elasticsearch-sql/releases/download/2.4.1.0/elasticsearch-sql-2.4.1.0.zip
